# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/InsuranceAI',
                'doc_host': 'https://bsalanie.github.io',
                'git_url': 'https://github.com/bsalanie/InsuranceAI',
                'lib_path': 'InsuranceAI'},
  'syms': { 'InsuranceAI.core': {'InsuranceAI.core.foo': ('core.html#foo', 'InsuranceAI/core.py')},
            'InsuranceAI.utils': { 'InsuranceAI.utils.read_data': ('core.html#read_data', 'InsuranceAI/utils.py'),
                                   'InsuranceAI.utils.select_variables': ('core.html#select_variables', 'InsuranceAI/utils.py')}}}