# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_data', 'select_variables']

# %% ../nbs/00_core.ipynb 3
from typing import Tuple
from pathlib import Path
import pandas as pd

# %% ../nbs/00_core.ipynb 5
def read_data(dataset: str): # -> pd.DataFrame:
    """
    Reads the 
    """
    data_path = Path("../Datasets")
    data_file = f"{dataset}.txt"
    names_vars = [
        'Age below 25', 'Age', 'Age of driver', 'German car', 'American car', 'Age of License',
                  'Type of deductible', 'Theft deductible', 'Compulsory coverage', 'Comprehensive coverage',
                  'Responsibility', 'Citroën', 'Driver is insuree', 'No accident', 
                    'Responsibility code', 'Company',
                  'Date car', 'Department registered', 'Year birth insuree', 'Claim processing',
                  'Other french car', 'Group', 'Guarantee in claim', 'Male', 'Not at fault', 
                  'Italian car', 'Number cars in claim', 'Department claim', 'Deductible damages',
                  'Deductible theft', 'Reimbursement', 'Settlement', 'Total cost', 'Compulsory cost', 'Nature claim', 
                  'Number claims at fault', 'Identifier 1', 'Identifier 2', 'Basic premium',
                  'Peugeot', 'Fiscal HP', 'Total premium', 'Duration', 'Occupation', 'Number claims',
                  'Compulsory premium', 'Region', 'Renault', 'Class car', 'Gender', 'Real group',
                  'Bonus Malus', 'Age category car', 'Age category insuree', 'Basic premium category', 
                  'Shared responsibility', 'Car use', 'Zone'
                 ]
    data = pd.read_csv(data_path / data_file, delimiter = ' ', header=None)
    data.columns = names_vars
    # we change the types of the non-categorical variables
    for float_col in ['Deductible damages', 'Deductible theft', 'Reimbursement', 'Total cost', 'Compulsory cost',
                     'Total premium', 'Bonus Malus']:
        data[float_col]=data[float_col].astype(float)
    return data

# %% ../nbs/00_core.ipynb 6
def select_variables(data): # pd.DataFrame) -> Tuple[pd.Series, pd.Series, pd.Series, pd.DataFrame]:
    """ returns the `y` variables, the weights, and the `X` covariates"""
    y1 = 1*(data['Comprehensive coverage'] > 0)
    y2 = 1*(data['Not at fault'] == 0)
    w = data['Duration']

    X = data[['Group', 'Male', 'Occupation', 'Region', 'Renault', 'Age category car',
           'Age category insuree', 'Car use', 'Zone']].astype('category')

    return y1, y2, w, X
